// The formats the Battle tab offers. Each entry maps a UI button to an engine
// format id (the actual @pkmn/sim format that runs the battle).
//
// - gen9randombattle: singles, teams auto-generated by @pkmn/randoms.
// - VGC Reg I / Reg MB: doubles + team preview. Both run on gen9vgc2025regi — the
//   newest VGC ruleset the in-browser engine (@pkmn/sim) supports. The 2026
//   "Champions" Reg M-B data is NOT in the engine, so the Reg MB button runs on
//   that latest supported ruleset (noted in the UI). VGC has no team generator, so
//   each format ships legal, pre-validated sample teams (checked with the real
//   gen9vgc2025regi TeamValidator).

export type FormatKey = "gen9randombattle" | "vgcregi" | "vgcregmb";

export interface FormatDef {
  key: FormatKey;
  label: string;
  engineFormat: string; // actual @pkmn/sim format id passed to the simulator
  gametype: "singles" | "doubles";
  teamPreview: boolean;
  teamSize: number; // how many are brought to the field (pick N)
  packedTeams?: string[]; // when set, teams come from here instead of the generator
  note?: string; // small clarifying caption under the picker
}

// --- Legal gen9vgc2025regi teams (level 50, no restricted Pokémon). ---
// Verified: new TeamValidator("gen9vgc2025regi").validateTeam(...) => no problems.

const REGI_A =
  "Incineroar||SafetyGoggles|Intimidate|FakeOut,KnockOff,FlareBlitz,PartingShot|Adamant|244,4,4,,20,236||||50|]" +
  "Rillaboom||AssaultVest|GrassySurge|FakeOut,GrassyGlide,WoodHammer,Uturn|Adamant|252,116,,,140,||||50|]" +
  "Flutter Mane||FocusSash|Protosynthesis|Moonblast,ShadowBall,DazzlingGleam,Protect|Timid|,,4,252,,252||||50|]" +
  "Landorus-Therian||LifeOrb|Intimidate|Earthquake,RockSlide,Uturn,Protect|Jolly|4,252,,,,252||||50|]" +
  "Amoonguss||RockyHelmet|Regenerator|Spore,RagePowder,PollenPuff,Protect|Calm|236,,172,,100,||||50|]" +
  "Urshifu-Rapid-Strike||MysticWater|UnseenFist|SurgingStrikes,CloseCombat,AquaJet,Protect|Adamant|4,252,,,,252||||50|";

const REGI_B =
  "Gholdengo||ChoiceScarf|GoodasGold|MakeItRain,ShadowBall,Thunderbolt,Trick|Timid|,,4,252,,252||||50|]" +
  "Iron Hands||AssaultVest|QuarkDrive|FakeOut,WildCharge,DrainPunch,IcePunch|Adamant|100,252,,,156,||||50|]" +
  "Chi-Yu||ChoiceSpecs|BeadsofRuin|HeatWave,DarkPulse,Overheat,Snarl|Modest|,,4,252,,252||||50|]" +
  "Dragonite||SitrusBerry|Multiscale|ExtremeSpeed,IceSpinner,TeraBlast,Protect|Adamant|252,116,,,,140||||50|]" +
  "Grimmsnarl||LightClay|Prankster|Reflect,LightScreen,SpiritBreak,ThunderWave|Careful|252,4,,,252,||||50|]" +
  "Garchomp||LifeOrb|RoughSkin|Earthquake,DragonClaw,RockSlide,Protect|Jolly|4,252,,,,252||||50|";

// Distinct pool for the Reg MB button (also legal gen9vgc2025regi).
const REGMB_C =
  "Torkoal||Charcoal|Drought|Eruption,HeatWave,EarthPower,Protect|Quiet|252,,4,252,,||,,,,,0||50|]" +
  "Hatterene||LifeOrb|MagicBounce|ExpandingForce,DazzlingGleam,MysticalFire,TrickRoom|Quiet|252,,,252,4,||,,,,,0||50|]" +
  "Indeedee-F||PsychicSeed|PsychicSurge|FollowMe,TrickRoom,DazzlingGleam,HelpingHand|Sassy|252,,172,,84,||,,,,,0||50|]" +
  "Ursaluna||FlameOrb|Guts|Facade,HeadlongRush,Crunch,Protect|Brave|252,252,,,4,||,,,,,0||50|]" +
  "Kingambit||AssaultVest|Defiant|KowtowCleave,SuckerPunch,IronHead,LowKick|Brave|252,252,,,4,||,,,,,0||50|]" +
  "Amoonguss||RockyHelmet|Regenerator|Spore,RagePowder,PollenPuff,Protect|Sassy|236,,172,,100,||,,,,,0||50|";

const REGMB_D =
  "Tornadus||FocusSash|Prankster|BleakwindStorm,Tailwind,Taunt,Protect|Timid|,,4,252,,252||||50|]" +
  "Archaludon||PowerHerb|Stamina|ElectroShot,FlashCannon,DracoMeteor,BodyPress|Modest|252,,100,156,,||||50|]" +
  "Ursaluna-Bloodmoon||LifeOrb|MindsEye|BloodMoon,EarthPower,HyperVoice,Protect|Modest|252,,4,252,,||,,,,,0||50|]" +
  "Rillaboom||MiracleSeed|GrassySurge|GrassyGlide,FakeOut,HighHorsepower,Protect|Adamant|252,252,,,4,||||50|]" +
  "Flutter Mane||BoosterEnergy|Protosynthesis|Moonblast,ShadowBall,IcyWind,Protect|Timid|,,4,252,,252||||50|]" +
  "Iron Hands||AssaultVest|QuarkDrive|FakeOut,WildCharge,DrainPunch,IcePunch|Adamant|100,252,,,156,||||50|";

export const FORMATS: Record<FormatKey, FormatDef> = {
  gen9randombattle: {
    key: "gen9randombattle",
    label: "Gen 9 Random Battle",
    engineFormat: "gen9randombattle",
    gametype: "singles",
    teamPreview: false,
    teamSize: 6,
  },
  vgcregi: {
    key: "vgcregi",
    label: "VGC 2025 Reg I",
    engineFormat: "gen9vgc2025regi",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: [REGI_A, REGI_B],
  },
  vgcregmb: {
    key: "vgcregmb",
    label: "VGC Reg MB",
    engineFormat: "gen9vgc2025regi",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: [REGMB_C, REGMB_D],
    note: "Reg MB runs on the engine's latest supported VGC ruleset (2025 Reg I) — the 2026 Champions Reg M-B data isn't in the in-browser engine yet.",
  },
};

export const FORMAT_LIST: FormatDef[] = [FORMATS.gen9randombattle, FORMATS.vgcregi, FORMATS.vgcregmb];
