// The formats the Battle tab offers. Each entry maps a UI button to an engine
// format id (the actual @pkmn/sim format that runs the battle).
//
// - gen9randombattle: singles, teams auto-generated by @pkmn/randoms.
// - VGC 2025 Reg I: doubles + team preview, allows up to two Restricted Legendaries.
// - VGC 2026 Reg M-B: its own ruleset, built from Reg I by hard-banning the whole
//   Restricted Legendary class (and dropping the "up to two" allowance) — Mythicals
//   are already banned by Flat Rules. That reproduces Reg M-B's real structure on the
//   Gen 9 engine: Lv 50 doubles, Open Team Sheets, Species/Item/Nickname clauses,
//   bring 6 pick 4, and Mega Evolution (the Mega Stones + formes the teams use are unbanned
//   below). What it can't reproduce is Champions-only Pokémon (that data isn't in @pkmn/sim).
//   The UI note says so. VGC has no team generator, so each format ships pre-packed sample
//   teams (see reg-mb-teams.ts).

import { REG_MB_PACKED } from "./reg-mb-teams";

export type FormatKey = "gen9randombattle" | "vgcregi" | "vgcregmb";

export interface FormatDef {
  key: FormatKey;
  label: string;
  engineFormat: string; // actual @pkmn/sim format id passed to the simulator
  gametype: "singles" | "doubles";
  teamPreview: boolean;
  teamSize: number; // how many are brought to the field (pick N)
  packedTeams?: string[]; // when set, teams come from here instead of the generator
  note?: string; // small clarifying caption under the picker
}

// --- Legal VGC teams (level 50, no Restricted Legendaries or Mythicals). ---
// Verified with the real TeamValidator: Reg I teams pass gen9vgc2025regi, and the
// Reg M-B teams pass the stricter Reg-M-B ruleset below (no problems).

const REGI_A =
  "Incineroar||SafetyGoggles|Intimidate|FakeOut,KnockOff,FlareBlitz,PartingShot|Adamant|244,4,4,,20,236||||50|]" +
  "Rillaboom||AssaultVest|GrassySurge|FakeOut,GrassyGlide,WoodHammer,Uturn|Adamant|252,116,,,140,||||50|]" +
  "Flutter Mane||FocusSash|Protosynthesis|Moonblast,ShadowBall,DazzlingGleam,Protect|Timid|,,4,252,,252||||50|]" +
  "Landorus-Therian||LifeOrb|Intimidate|Earthquake,RockSlide,Uturn,Protect|Jolly|4,252,,,,252||||50|]" +
  "Amoonguss||RockyHelmet|Regenerator|Spore,RagePowder,PollenPuff,Protect|Calm|236,,172,,100,||||50|]" +
  "Urshifu-Rapid-Strike||MysticWater|UnseenFist|SurgingStrikes,CloseCombat,AquaJet,Protect|Adamant|4,252,,,,252||||50|";

const REGI_B =
  "Gholdengo||ChoiceScarf|GoodasGold|MakeItRain,ShadowBall,Thunderbolt,Trick|Timid|,,4,252,,252||||50|]" +
  "Iron Hands||AssaultVest|QuarkDrive|FakeOut,WildCharge,DrainPunch,IcePunch|Adamant|100,252,,,156,||||50|]" +
  "Chi-Yu||ChoiceSpecs|BeadsofRuin|HeatWave,DarkPulse,Overheat,Snarl|Modest|,,4,252,,252||||50|]" +
  "Dragonite||SitrusBerry|Multiscale|ExtremeSpeed,IceSpinner,TeraBlast,Protect|Adamant|252,116,,,,140||||50|]" +
  "Grimmsnarl||LightClay|Prankster|Reflect,LightScreen,SpiritBreak,ThunderWave|Careful|252,4,,,252,||||50|]" +
  "Garchomp||LifeOrb|RoughSkin|Earthquake,DragonClaw,RockSlide,Protect|Jolly|4,252,,,,252||||50|";

export const FORMATS: Record<FormatKey, FormatDef> = {
  gen9randombattle: {
    key: "gen9randombattle",
    label: "Gen 9 Random Battle",
    engineFormat: "gen9randombattle",
    gametype: "singles",
    teamPreview: false,
    teamSize: 6,
  },
  vgcregi: {
    key: "vgcregi",
    label: "VGC 2025 Reg I",
    engineFormat: "gen9vgc2025regi",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: [REGI_A, REGI_B],
  },
  vgcregmb: {
    key: "vgcregmb",
    label: "VGC 2026 Reg M-B",
    // Reg I + hard ban on all Restricted Legendaries (Reg I allowed two), the Champions 66-EV
    // budget, Terastal Clause (Champions replaces Tera with Mega — no Terastallizing), and Mega
    // Evolution re-enabled by unbanning the Mega Stones + formes the teams use.
    // No space after commas: the battle engine splits @@@ rules on "," without trimming.
    engineFormat:
      "gen9vgc2025regi@@@!Limit Two Restricted,-Restricted Legendary,!EV Limit,EV Limit = 66,Terastal Clause,+Gardevoirite,+Gardevoir-Mega,+Baxcalibrite,+Baxcalibur-Mega,+Swampertite,+Swampert-Mega,+Aerodactylite,+Aerodactyl-Mega,+Charizardite Y,+Charizard-Mega-Y",
    gametype: "doubles",
    teamPreview: true,
    teamSize: 4,
    packedTeams: REG_MB_PACKED,
    note: "Real Reg M-B ruleset: Lv 50 doubles, Open Team Sheets, no Mythicals or Restricted Legendaries, bring 6 pick 4. Champions training — 66 EV points per Pokémon (max 32 in one stat), each adds +1 to that stat (IVs unused). Mega Evolution replaces Terastallization: a Pokémon holding its Mega Stone can Mega Evolve once per battle, and Tera is disabled. Champions-only Pokémon aren't in the in-browser Gen 9 engine.",
  },
};

export const FORMAT_LIST: FormatDef[] = [FORMATS.gen9randombattle, FORMATS.vgcregi, FORMATS.vgcregmb];
